/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* SysInt_SW */
    const cy_stc_sysint_t SysInt_SW_cfg = {
        .intrSrc = (IRQn_Type)SysInt_SW__INTC_NUMBER,
        .intrPriority = SysInt_SW__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_SW3 */
    const cy_stc_sysint_t SysInt_SW3_cfg = {
        .intrSrc = (IRQn_Type)SysInt_SW3__INTC_NUMBER,
        .intrPriority = SysInt_SW3__INTC_CORTEXM4_PRIORITY
    };

    /* UART_DEBUG_SCB_IRQ */
    const cy_stc_sysint_t UART_DEBUG_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)UART_DEBUG_SCB_IRQ__INTC_NUMBER,
        .intrPriority = UART_DEBUG_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_Tick */
    const cy_stc_sysint_t SysInt_Tick_cfg = {
        .intrSrc = (IRQn_Type)SysInt_Tick__INTC_NUMBER,
        .intrPriority = SysInt_Tick__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_ULFBasebandCnt */
    const cy_stc_sysint_t SysInt_ULFBasebandCnt_cfg = {
        .intrSrc = (IRQn_Type)SysInt_ULFBasebandCnt__INTC_NUMBER,
        .intrPriority = SysInt_ULFBasebandCnt__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_ULFMainCnt */
    const cy_stc_sysint_t SysInt_ULFMainCnt_cfg = {
        .intrSrc = (IRQn_Type)SysInt_ULFMainCnt__INTC_NUMBER,
        .intrPriority = SysInt_ULFMainCnt__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_ULFCarrierCnt */
    const cy_stc_sysint_t SysInt_ULFCarrierCnt_cfg = {
        .intrSrc = (IRQn_Type)SysInt_ULFCarrierCnt__INTC_NUMBER,
        .intrPriority = SysInt_ULFCarrierCnt__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

