/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* SysInt_SW */
#define SysInt_SW__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_SW__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_SW__INTC_NUMBER 0u
#define SysInt_SW_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_SW_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_SW_INTC_NUMBER 0u

/* SysInt_SW3 */
#define SysInt_SW3__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_SW3__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_SW3__INTC_NUMBER 10u
#define SysInt_SW3_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_SW3_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_SW3_INTC_NUMBER 10u

/* SysInt_Tick */
#define SysInt_Tick__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_Tick__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_Tick__INTC_NUMBER 91u
#define SysInt_Tick_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_Tick_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_Tick_INTC_NUMBER 91u

/* SysInt_ULFMainCnt */
#define SysInt_ULFMainCnt__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_ULFMainCnt__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_ULFMainCnt__INTC_NUMBER 93u
#define SysInt_ULFMainCnt_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_ULFMainCnt_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_ULFMainCnt_INTC_NUMBER 93u

/* UART_DEBUG_SCB_IRQ */
#define UART_DEBUG_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_DEBUG_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_DEBUG_SCB_IRQ__INTC_NUMBER 46u
#define UART_DEBUG_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_DEBUG_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_DEBUG_SCB_IRQ_INTC_NUMBER 46u

/* SysInt_ULFCarrierCnt */
#define SysInt_ULFCarrierCnt__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_ULFCarrierCnt__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_ULFCarrierCnt__INTC_NUMBER 90u
#define SysInt_ULFCarrierCnt_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_ULFCarrierCnt_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_ULFCarrierCnt_INTC_NUMBER 90u

/* SysInt_ULFBasebandCnt */
#define SysInt_ULFBasebandCnt__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_ULFBasebandCnt__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_ULFBasebandCnt__INTC_NUMBER 92u
#define SysInt_ULFBasebandCnt_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_ULFBasebandCnt_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_ULFBasebandCnt_INTC_NUMBER 92u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
